In [5]:
#Unv.: Anarata Diaz Mario

#Librerias
import numpy as np 
from Rata import Rata

#Valores constantes
VACIO = 0
MURO = 1
QUESO = 2
RATA = 3

"""
En un ambiente:
0: vacío
1: muro
2: queso
3: rata
Lectura del archivo de ambiente
"""

ambiente = [[0, 0, 0, 0],
            [0, 1, 1, 2],
            [3, 1, 0, 0],
            [0, 0, 0, 1]]

ambiente = np.array(ambiente, dtype=np.int32)

# Encontrar la posicion de la rata en el ambiente inicial
def hallarPosicionRata():
  count = 0
  for i in range(len(ambiente)):
    for j in range(len(ambiente[0])):
      if ambiente[i][j] == RATA:
        if count == 0:
          first_i, first_j = i,j
        count += 1
  if count > 1:
     raise Exception("No se permite que haya mas de una posicion para la rata")
  elif count == 1:
    return first_i, first_j
  else:
    raise Exception("Debe haber al menos una posicion para la rata")      


"""
En la matriz de decisión:
0: libre / no huele a queso
1: no libre / huele a queso
En las acciones:
0: izquierda
1: arriba
2: derecha
3: abajo
-1: movimiento no válido
Leer tabla de decisión del archivo en matriz Filas
"""

filas = [[0, 0, 0, 0, 1],
        [0, 0, 0, 1, 1],
        [0, 0, 1, 0, 1],
        [0, 0, 1, 1, 1],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 1, 2],
        [0, 1, 1, 0, 0],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 1, 2],
        [1, 0, 1, 0, 3],
        [1, 0, 1, 1, 1],
        [1, 1, 0, 0, 2],
        [1, 1, 0, 1, 2],
        [1, 1, 1, 0, 3],
        [1, 1, 1, 1, -1]]

filas = np.array(filas, dtype=np.int32)

"""
 Función para crear matriz de decisión donde los índices indican lo que se ve
"""
def crearMatrizDecision():
  matrizDecision = np.empty((2, 2, 2, 2))
  for fila in filas:
    matrizDecision[fila[0]][fila[1]][fila[2]][fila[3]] = fila[4]
  return matrizDecision.astype(int)

matrizDecision = crearMatrizDecision()

#Creacion de rata
filaRata, columnaRata = hallarPosicionRata()
rata = Rata(filaRata, columnaRata)

# Ejecución automática según la tabla de decisión 
# Se detiene si encuentra el queso o con un número máximo de movimientos
counter = 0
MAX_MOVIMIENTOS = 10
while not rata.tuvoExito and counter <= MAX_MOVIMIENTOS: 
  rata.definirMovimiento(ambiente, matrizDecision)
  rata.moverse(ambiente)
  print("Estado del ambiente", counter)
  print(ambiente)
  counter += 1

if rata.tuvoExito:
  print("La rata encontró el queso")

Estado del ambiente 0
[[0 0 0 0]
 [0 1 1 2]
 [0 1 0 0]
 [3 0 0 1]]
Estado del ambiente 1
[[0 0 0 0]
 [0 1 1 2]
 [0 1 0 0]
 [0 3 0 1]]
Estado del ambiente 2
[[0 0 0 0]
 [0 1 1 2]
 [0 1 0 0]
 [0 0 3 1]]
Estado del ambiente 3
[[0 0 0 0]
 [0 1 1 2]
 [0 1 3 0]
 [0 0 0 1]]
Estado del ambiente 4
[[0 0 0 0]
 [0 1 1 2]
 [0 1 0 3]
 [0 0 0 1]]
Estado del ambiente 5
[[0 0 0 0]
 [0 1 1 3]
 [0 1 0 0]
 [0 0 0 1]]
La rata encontró el queso
